#compilar o front
FROM node:20.10.0 AS build

COPY ./webapp /home/arhenas/webapp/

WORKDIR /home/arhenas/webapp

RUN npm install
RUN npm run build


# executando ngnix para os arquivos compilados
FROM nginx:alpine

COPY --from=build /home/arhenas/webapp/dist/webapp/browser/ /usr/share/nginx/html/
ADD ./config/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]