# Generated by Django 5.0.4 on 2024-04-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("data_nasc", models.DateField()),
                ("cpf", models.CharField(max_length=14)),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Feminino")], max_length=1
                    ),
                ),
                ("altura", models.FloatField()),
                ("peso", models.FloatField()),
            ],
        ),
    ]
